default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: vinhnx

development:
  <<: *default
  database: incubit_development

test:
  <<: *default
  database: incubit_test

  #production:
  #  <<: *default
  #  database: incubit_production
  #  username: incubit
  #  password: <%= ENV['INCUBIT_DATABASE_PASSWORD'] %>
